&id001 !!python/object/new:__main__.RunInfo
dictitems:
  basefolder: /home/kai/Dropbox/DeepDrawData/analysis-data/
  datafraction: 0.5
  dirr2threshold: 0.2
  expid: 102
  model_experiment_id: 4
  randomseed: 2000
  randomseed_traintest: 42
  verbose: 0
state: *id001
